---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres
  namespace: jellystat
spec:
  target:
    name: postgres
    deletionPolicy: Delete
  data:
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: c744825e-4b48-49f2-96a3-63d3c4e957b1
        metadataPolicy: None
        property: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
    - secretKey: username
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: c744825e-4b48-49f2-96a3-63d3c4e957b1
        metadataPolicy: None
        property: username
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jellystat-jwt
  namespace: jellystat
spec:
  target:
    name: jellystat-jwt
    deletionPolicy: Delete
  data:
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: c867cd1f-6a97-4749-b0c5-021f5df332e1
        metadataPolicy: None
        property: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
